### ISSUE TITLE
Can't Communicate

### ISSUE THREAD

**Issue by dedhdude** [plcpeople/nodepccc#18]
I am not able to communicate with Micro 820.
Cant understand data types.
Kindly Please Help.

**Comment by plcpeople** [comment]
The Micro 820 apparently doesn't support PCCC so the nodepccc package is not going to work for you.  If you like the way this package works the 820 will support Modbus/TCP so the nodembtcpprotocol package https://github.com/plcpeople/mbtcpprotocol will work, and if you have issues getting going please open an issue in that project.  Since Modbus/TCP is common and open there are many other packages that support it as well.  I hope to one day write a driver that supports named tags for AB PLCs but have not had time.

**Comment by Jotan** [comment]
If you want to work with Modbus/TCP protocol I use [https://github.com/razakj/modbusjs](url), with a micrologix 1400, I never work with the micro 820, so I don't know how to configure the modbus protocol. But if you need help I can show you how to configure the 1400 controller.
